---
- name: Deploying w/ Ansible
  hosts: _Blue_Rental_Task4
  gather_facts: no
  become: yes
  remote_user: ubuntu

  vars:
    aws_region: us-east-1
    aws_account_id: "621627302500"
    ecr_registry: "621627302500.dkr.ecr.us-east-1.amazonaws.com"

  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Download AWS CLI installation script
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI installation script
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Run AWS CLI install script
      command: /tmp/aws/install

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository to APT sources
      shell: >
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Log in to AWS ECR
      shell: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 621627302500.dkr.ecr.us-east-1.amazonaws.com
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: aws_cli_result
      tags:
        - login_to_aws_ecr

    - name: Install K3S
      shell: curl -sfL https://get.k3s.io | sh -
      
    - name: Set permissions for k3s.yaml
      file:
        path: /etc/rancher/k3s/k3s.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Set KUBECONFIG environment variable permanently
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml'
        create: yes
      become_user: ubuntu

    - name: Download kompose
      shell: curl -L https://github.com/kubernetes/kompose/releases/download/v1.33.0/kompose-linux-amd64 -o kompose

    - name: Install kompose using snap
      snap:
        name: kompose
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Download docker-compose
      shell: >
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Set permissions for docker-compose
      file:
        path: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Copy docker-compose.yml to the server
      copy:
        src: "{{ compose_dir }}/docker-compose.yml"
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu 
        group: ubuntu 
        mode: '0664' 

    - name: Ensure kompose is executable
      file:
        path: /home/ubuntu/kompose
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Convert docker-compose file
      become: yes
      become_user: ubuntu
      command: /home/ubuntu/kompose convert -f /home/ubuntu/docker-compose.yml

    - name: Copy script to instance
      copy:
        src: "{{ convert_dir }}/kompose-convert.sh"
        dest: /home/ubuntu/kompose-convert.sh
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Execute Convert Script 
      become: yes
      become_user: ubuntu
      command: /home/ubuntu/kompose-convert.sh

    - name: Delete docker-compose.yml
      become: yes
      become_user: ubuntu
      file:
        path: /home/ubuntu/docker-compose.yml
        state: absent

    - name: Install Amazon ECR Credential Helper
      apt:
        name: amazon-ecr-credential-helper
        state: present
        update_cache: yes  # Ensure the package database is updated before installing

    - name: Pull blue-rental-car:reactv1
      become: yes
      become_user: ubuntu
      shell: docker pull 621627302500.dkr.ecr.us-east-1.amazonaws.com/ziyaasici/blue-rental-car:reactv1

    - name: Pull blue-rental-car:javav1
      become: yes
      become_user: ubuntu
      shell: docker pull 621627302500.dkr.ecr.us-east-1.amazonaws.com/ziyaasici/blue-rental-car:javav1

    - name: Pull blue-rental-car:postgresqlv1
      become: yes
      become_user: ubuntu
      shell: docker pull 621627302500.dkr.ecr.us-east-1.amazonaws.com/ziyaasici/blue-rental-car:postgresqlv1

    - name: Deploy Application  
      become: yes
      become_user: ubuntu
      command: kubectl apply -f .
