resources:
  - app-deployment.yaml
  - app-service.yaml
  - db-deployment.yaml
  - db-service.yaml
  - ui-deployment.yaml
  - ui-ingress.yaml
  - ui-service.yaml

images:
  - name: IMAGE_TAG_UI
    newName: "${IMAGE_TAG_FE}"
  - name: IMAGE_TAG_API
    newName: "${IMAGE_TAG_BE}"
  - name: IMAGE_TAG_PSTGRE
    newName: "${IMAGE_TAG_DB}"

namespace: brc