version: "3.7"

services:
    postgresql:
      image: 621627302500.dkr.ecr.us-east-1.amazonaws.com/ziyaasici/blue-rental-car:postgresqlv1
      environment:
        POSTGRES_USER: techprodb_user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: carrental
      networks:
        - blue-rental-car
      ports:
        - "5432:5432"
    
    react:
      image: 621627302500.dkr.ecr.us-east-1.amazonaws.com/ziyaasici/blue-rental-car:reactv1
      restart: always
      environment:
        REACT_APP_API_URL: http://3.84.185.234:8080/car-rental/api/ # DEGISTIRILECEK !!!!!!
      depends_on:
        - postgresql
      ports:
        - "3000:3000"
      networks:
        - blue-rental-car

    java:
      image: 621627302500.dkr.ecr.us-east-1.amazonaws.com/ziyaasici/blue-rental-car:javav1
      restart: always
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/carrental
        SPRING_DATASOURCE_USERNAME: techprodb_user
        SPRING_DATASOURCE_PASSWORD: password
      depends_on:
        - postgresql
      ports:
        - "8080:8080"
      networks:
        - blue-rental-car

networks:
    blue-rental-car:
        driver: bridge