apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-secret: regcred
    kompose.service.expose: {{ .Values.DNS_NAME }}
    kompose.service.nodeport.port: "30001"
    kompose.service.type: nodeport
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.DNS_NAME }}
      http:
        paths:
          - backend:
              service:
                name: ui
                port:
                  number: 3000
            path: /
            pathType: Prefix
          - path: /car-rental/api/
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 8080
